// integrate-with-svelte/src/App.svelte
<script>
  import CreativeEditorSDK from './lib/CreativeEditorSDK.svelte';
  const config = {
    license: 'vERESgSXbYj5Rs-FF4DzkMvhdQLh0Mxe6AD8V-doP6wqe_gmYmx_oUKqIlMkwpMu',
    userId: 'guides-user',
    // Enable local uploads in Asset Library
    callbacks: { onUpload: 'local' }
  };
</script>

<CreativeEditorSDK {config} />

// integrate-with-vue/src/App.vue
<template>
  <CreativeEditor :config="editorConfig" />
</template>

<script>
import CreativeEditor from './components/CreativeEditor.vue';

export default {
  name: 'App',
  components: { CreativeEditor },
  data() {
    return {
      editorConfig: {
        license: 'vERESgSXbYj5Rs-FF4DzkMvhdQLh0Mxe6AD8V-doP6wqe_gmYmx_oUKqIlMkwpMu',
        userId: 'guides-user',
        baseURL: 'https://cdn.img.ly/packages/imgly/cesdk-js/1.52.0-rc.1/assets',
        callbacks: {
          onUpload: 'local'
        }
      }
    };
  }
};
</script>
