// integrate-with-svelte-headless-ui/src/lib/CustomEditor.svelte
<script>
  import { onMount } from 'svelte';
  import CreativeEngine from '@cesdk/engine';

  // to store the DOM container where the CreativeEngine canvas will be attached
  let canvasContainer;
  // to store the CreativeEngine instance
  let engine;
  // to store the ID of the image block added to the scene
  let imageBlockId = null;

  onMount(async () => {
    // your CE.SDK configurations
    const config = {
      license:
        'vERESgSXbYj5Rs-FF4DzkMvhdQLh0Mxe6AD8V-doP6wqe_gmYmx_oUKqIlMkwpMu', // replace it with your license key
      userId: 'guides-user',
      baseURL: 'https://cdn.img.ly/packages/imgly/cesdk-engine/1.59.1/assets'
    };

    // initialize CreativeEngine in headless mode
    engine = await CreativeEngine.init(config);

    // append CE.SDK canvas to the DOM (optional)
    if (canvasContainer && engine.element) {
      canvasContainer.appendChild(engine.element);
    }

    // get the current scene or create a new one
    let scene = engine.scene.get();
    if (!scene) {
      scene = engine.scene.create();
      const page = engine.block.create('page');
      engine.block.appendChild(scene, page);
    }

    // get the first page block
    const [page] = engine.block.findByType('page');

    // append a block to show an image on the page
    const imageBlock = engine.block.create('graphic');
    imageBlockId = imageBlock;
    engine.block.setShape(imageBlock, engine.block.createShape('rect'));

    // fill the block with an image from a public source
    const imageFill = engine.block.createFill('image');
    engine.block.setSourceSet(imageFill, 'fill/image/sourceSet', [
      {
        uri: 'https://img.ly/static/ubq_samples/sample_1_1024x683.jpg',
        width: 1024,
        height: 683
      }
    ]);
    engine.block.setFill(imageBlock, imageFill);
    engine.block.appendChild(page, imageBlock);

    // zoom to fit the page in the editor view
    engine.scene.zoomToBlock(page);
  });

  // callback to change the opacity of the image
  function changeOpacity() {
    if (engine && imageBlockId != null) {
      // get the current opacity value of the image
      const currentOpacity = engine.block.getOpacity(imageBlockId);
      // reduce the opacity of the image by 20% at each click
      engine.block.setOpacity(imageBlockId, currentOpacity * 0.8);
    }
  }
</script>

<div class="editor-container">
  <div class="canvas-container" bind:this={canvasContainer}></div>
  <div class="button-overlay">
    <button on:click={changeOpacity}>Reduce Opacity</button>
  </div>
</div>

<style>
  .editor-container {
    width: 100vw;
    height: 100vh;
    position: relative;
  }

  .canvas-container {
    width: 100%;
    height: 100%;
  }

  .button-overlay {
    position: absolute;
    top: 20px;
    left: 20px;
  }

  .button-overlay button {
    border-radius: 8px;
    border: 1px solid #ccc;
    padding: 0.6em 1.2em;
    font-size: 1em;
    font-weight: 500;
    font-family: inherit;
    background-color: #ffffff;
    color: #1a1a1a;
    cursor: pointer;
    transition:
      border-color 0.25s,
      box-shadow 0.25s;
    box-shadow: 0 2px 6px rgba(0, 0, 0, 0.1);
  }

  .button-overlay button:hover {
    border-color: #646cff;
    box-shadow: 0 4px 10px rgba(100, 108, 255, 0.2);
  }

  .button-overlay button:focus,
  .button-overlay button:focus-visible {
    outline: 2px solid #646cff;
    outline-offset: 2px;
  }
</style>

// integrate-with-react-headless-ui/src/CustomEditor.jsx
import CreativeEngine from '@cesdk/engine';
import { useCallback, useEffect, useRef } from 'react';

export default function CustomEditor() {
  // reference to store the DOM container where the CreativeEngine canvas will be attached
  const canvasRef = useRef(null);
  // reference to store the CreativeEngine instance
  const engineRef = useRef(null);
  // reference to store the the ID of the image block added to the scene
  const imageBlockIdRef = useRef(null);

  useEffect(() => {
    // your CE.SDK configurations
    const config = {
      license:
        'vERESgSXbYj5Rs-FF4DzkMvhdQLh0Mxe6AD8V-doP6wqe_gmYmx_oUKqIlMkwpMu', // replace it with your license key
      userId: 'guides-user',
      baseURL: 'https://cdn.img.ly/packages/imgly/cesdk-engine/1.51.0-rc.3/assets'
    };

    // initialize CreativeEngine in headless mode
    CreativeEngine.init(config).then((engine) => {
      // to avoid initializing CreativeEngine twice in strict mode
      if (!engineRef.current) {
        engineRef.current = engine;

        // append CE.SDK canvas to the DOM
        if (canvasRef.current) {
          canvasRef.current.appendChild(engine.element);
        }

        // get the current scene or create a new one
        let scene = engine.scene.get();
        if (!scene) {
          scene = engine.scene.create();
          const page = engine.block.create('page');
          engine.block.appendChild(scene, page);
        }

        // get the first page block
        const [page] = engine.block.findByType('page');

        // appen a block to show an image on the page
        const imageBlockId = engine.block.create('graphic');
        imageBlockIdRef.current = imageBlockId;
        engine.block.setShape(imageBlockId, engine.block.createShape('rect'));

        // fill the block with an image from a public source
        const imageFill = engine.block.createFill('image');
        engine.block.setSourceSet(imageFill, 'fill/image/sourceSet', [
          {
            uri: 'https://img.ly/static/ubq_samples/sample_1_1024x683.jpg',
            width: 1024,
            height: 683
          }
        ]);
        engine.block.setFill(imageBlockId, imageFill);
        engine.block.appendChild(page, imageBlockId);

        // zoom to fit the page in the editor view
        engine.scene.zoomToBlock(page);
      }
    });
  }, []);

  const changeOpacity = useCallback(() => {
    const engine = engineRef.current;
    const imageBlockId = imageBlockIdRef.current;

    if (engine && imageBlockId != null) {
      // get the current opacity value of the image
      const currentOpacity = engine.block.getOpacity(imageBlockId);
      // reduce the opacity image by 20% at each click
      engine.block.setOpacity(imageBlockId, currentOpacity * 0.8);
    }
  }, [engineRef, imageBlockIdRef]);

  return (
    <div style={{ width: '100vw', height: '100vh', position: 'relative' }}>
      <div ref={canvasRef} style={{ width: '100%', height: '100%' }} />
      <div style={{ position: 'absolute', top: 20, left: 20 }}>
        <button onClick={changeOpacity}>Reduce Opacity</button>
      </div>
    </div>
  );
}
