// integrate-with-svelte/src/lib/CreativeEditorSDK.svelte
<!-- docs-integrate-svelte-3 -->
<script>
  // docs-integrate-svelte-1
  import CreativeEditorSDK from '@cesdk/cesdk-js';
  // docs-integrate-svelte-1
  import { onDestroy, onMount } from 'svelte';

  let container;
  let cesdk = null;

  // docs-integrate-svelte-4
  onMount(() => {
    const { el, children, class: _, config, ...props } = $$props;
    try {
      CreativeEditorSDK.create(container, config).then(async (instance) => {
        cesdk = instance;
        // Do something with the instance of CreativeEditor SDK, for example:
        // Populate the asset library with default / demo asset sources.
        cesdk.addDefaultAssetSources();
        cesdk.addDemoAssetSources({ sceneMode: 'Design' });
        await cesdk.createDesignScene();
      });
    } catch (err) {
      console.warn(`CreativeEditor SDK failed to mount.`, { err });
    }
  });
  // docs-integrate-svelte-4

  onDestroy(() => {
    try {
      if (cesdk) {
        cesdk.dispose();
        cesdk = null;
      }
    } catch (err) {
      console.warn(`CreativeEditor SDK failed to unmount.`, { err });
    }
  });
</script>

<!-- docs-integrate-svelte-2 -->
<div id="cesdk_container" bind:this={container} />

<!-- docs-integrate-svelte-2 -->
<style>
  #cesdk_container {
    height: 100vh;
    width: 100vw;
  }
</style>
<!-- docs-integrate-svelte-3 -->

// integrate-with-react/src/CreativeEditorSDK.jsx
import './index.css';

// docs-integrate-react-1
import CreativeEditorSDK from '@cesdk/cesdk-js';
// docs-integrate-react-1

import { useEffect, useRef } from 'react';

// docs-integrate-react-3
const Component = (props = {}) => {
  // docs-integrate-react-4
  const cesdk_container = useRef(null);
  // docs-integrate-react-4
  useEffect(() => {
    if (cesdk_container.current) {
      CreativeEditorSDK.create(cesdk_container.current, props.config).then(
        async (instance) => {
          // Do something with the instance of CreativeEditor SDK, for example:
          // Populate the asset library with default / demo asset sources.
          instance.addDefaultAssetSources();
          instance.addDemoAssetSources({ sceneMode: 'Design' });
          await instance.createDesignScene();
        }
      );
    }
  }, [props, cesdk_container]);

  return (
    // docs-integrate-react-2
    <div
      ref={cesdk_container}
      style={{ width: '100vw', height: '100vh' }}
    ></div>
    // docs-integrate-react-2
  );
};
// docs-integrate-react-3

export default Component;
